import = [
    "~/.config/alacritty/themes/themes/rose-pine-moon.toml"
]

[window]
decorations="None"

[font]
normal= { family = "JetBrainsMonoNL Nerd Font Mono", style = "Regular"}
bold= { family = "JetBrainsMonoNL Nerd Font Mono", style = "Bold"}
italic= { family = "JetBrainsMonoNL Nerd Font Mono", style = "Italic"}
bold_italic= { family = "JetBrainsMonoNL Nerd Font Mono", style = "Bold Italic"}
size=12
